# Generated by Django 2.2.5 on 2023-11-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=100, verbose_name='Escola')),
                ('telefone_escola', models.CharField(max_length=9, verbose_name='Telefone')),
                ('nome_responsavel', models.CharField(max_length=50, verbose_name='Responsavel')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='Nome')),
                ('data_nasc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peca', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('cor', models.CharField(max_length=100, verbose_name='Cor')),
                ('tamanho', models.CharField(max_length=100, verbose_name='Tamanho')),
                ('doador', models.CharField(max_length=100, verbose_name='Doador')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaVisita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField()),
                ('qtd_pessoas', models.IntegerField()),
                ('responsavel_agendamento', models.CharField(max_length=100, verbose_name='Responsável')),
                ('turma', models.CharField(max_length=45, verbose_name='Turma')),
                ('nome_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Escola', verbose_name='Escola')),
                ('nome_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Funcionario', verbose_name='Funcionário')),
            ],
        ),
    ]
